const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let signals=[];const api=()=>$('#api-url').value.replace(/\/$/,'');
function money(v){return typeof v==='number'?`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—'}
function navigate(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#page-title').textContent={overview:'Market overview',signals:'Signal book',portfolio:'Paper portfolio',risk:'Risk & learning'}[view]||'Market overview';if(view==='portfolio')loadPortfolio();if(view==='risk')loadRisk()}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>navigate(b.dataset.viewLink));
async function get(path){const r=await fetch(api()+path);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function renderSignals(){const rows=signals.map(s=>`<div class="signal-row"><span class="ticker">${s.ticker}</span><span class="direction ${(s.direction||'').toLowerCase()}">${s.direction}</span><span class="confidence">${Number(s.confidence).toFixed(1)}%</span><span class="regime">${s.regime}</span></div>`).join('')||'<div class="empty">No signals returned.</div>';$('#signal-list').innerHTML=rows;$('#signals-table').innerHTML=`<table class="data-table"><thead><tr><th>Ticker</th><th>Direction</th><th>Confidence</th><th>Regime</th><th>Rationale</th></tr></thead><tbody>${signals.map(s=>`<tr><td><strong>${s.ticker}</strong></td><td class="direction ${(s.direction||'').toLowerCase()}">${s.direction}</td><td>${Number(s.confidence).toFixed(1)}%</td><td>${s.regime}</td><td>${s.rationale||'—'}</td></tr>`).join('')}</tbody></table>`}
async function loadPortfolio(){try{const p=await get('/portfolio');$('#portfolio-data').innerHTML=`<div class="kv"><div><span>Cash</span><strong>${money(p.cash_usd)}</strong></div><div><span>Equity</span><strong>${money(p.equity)}</strong></div><div><span>Return</span><strong>${p.total_return_pct.toFixed(2)}%</strong></div><div><span>Exposure</span><strong>${p.exposure_pct.toFixed(2)}%</strong></div></div><table class="data-table"><thead><tr><th>Ticker</th><th>Direction</th><th>Size</th><th>Status</th><th>P&L</th></tr></thead><tbody>${(p.trade_log||[]).map(t=>`<tr><td>${t.ticker}</td><td>${t.direction}</td><td>${money(t.size_usd)}</td><td>${t.status}</td><td>${t.pnl_usd==null?'—':money(t.pnl_usd)}</td></tr>`).join('')||'<tr><td colspan="5">No trades yet.</td></tr>'}</tbody></table>`;$('#equity').textContent=money(p.equity);$('#return').textContent=`${p.total_return_pct.toFixed(2)}%`;$('#exposure').textContent=`${p.exposure_pct.toFixed(2)}%`;$('#positions').textContent=p.open_positions}catch(e){$('#portfolio-data').innerHTML=`<div class="empty">${e.message}</div>`}}
async function loadRisk(){try{const r=await get('/risk-log');$('#risk-data').innerHTML=(r.decisions||[]).slice(-12).reverse().map(d=>`<div class="diag"><strong>${d.ticker||'PORTFOLIO'}</strong> · ${d.reason||d.message||JSON.stringify(d)}</div>`).join('')||'<div class="empty">No risk decisions logged.</div>'}catch(e){$('#risk-data').innerHTML=`<div class="empty">${e.message}</div>`}try{const l=await get('/learning/status');$('#learning-data').innerHTML=`<div class="kv"><div><span>Closed trades</span><strong>${l.closed_trades_logged}</strong></div><div><span>Wins / losses</span><strong>${l.wins} / ${l.losses}</strong></div><div><span>Ready to retrain</span><strong>${l.ready_to_retrain?'YES':'NO'}</strong></div><div><span>Weights</span><strong>S ${Number(l.current_weights.sentiment).toFixed(2)} · T ${Number(l.current_weights.technical).toFixed(2)} · R ${Number(l.current_weights.regime).toFixed(2)}</strong></div></div>`}catch(e){$('#learning-data').innerHTML=`<div class="empty">${e.message}</div>`}}
async function health(){try{await get('/health');$('#health').innerHTML='<span class="status-dot"></span> API online'}catch(e){$('#health').innerHTML='<span style="color:#ff8b8b">●</span> API unavailable'}}
async function scan(){const btn=$('#ingest');btn.disabled=true;btn.textContent='Scanning…';try{const r=await fetch(api()+'/ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tickers:{AAPL:'stock',TSLA:'stock',NVDA:'stock',SPY:'stock',BTC:'crypto',ETH:'crypto'},lookback_bars:90,news_lookback_hours:48})});const data=await r.json();if(!r.ok)throw new Error(data.detail?.message||'Ingestion failed');signals=data.signals||[];renderSignals();$('#diagnostics').innerHTML=Object.entries(data.diagnostics||{}).map(([t,d])=>`<div class="diag"><strong>${t}</strong> · ${d.ok?'OK':'SKIPPED'} · price: ${d.price_source_used||'—'} · news: ${d.news_source_used||'—'}</div>`).join('')||'<div class="empty">No diagnostics.</div>';await loadPortfolio()}catch(e){$('#diagnostics').innerHTML=`<div class="diag" style="color:#ff8b8b">${e.message}</div>`}finally{btn.disabled=false;btn.textContent='Run market scan'}}
$('#refresh').onclick=()=>{health();loadPortfolio();loadRisk()};$('#ingest').onclick=scan;$('#scan-signals').onclick=scan;health();loadPortfolio();