const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let signals=[];let refreshTimer;const api=()=>$('#api-url').value.trim().replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>typeof v==='number'?`$${v.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—';
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='toast',3500)}
function navigate(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#page-title').textContent={overview:'Market overview',signals:'Signal book',portfolio:'Paper portfolio',risk:'Risk & learning'}[view]||'Market overview';if(view==='portfolio')loadPortfolio();if(view==='risk')loadRisk()}
$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$$('[data-view-link]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
async function get(path){const r=await fetch(api()+path);let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail?.message||data.detail||`${r.status} ${r.statusText}`);return data}
function renderSignals(){signals=[...signals].sort((a,b)=>Number(b.confidence)-Number(a.confidence));const rows=signals.map(s=>`<div class="signal-row"><span class="ticker">${esc(s.ticker)}</span><span class="direction ${(s.direction||'').toLowerCase()}">${esc(s.direction)}</span><span class="confidence">${Number(s.confidence).toFixed(1)}%</span><span class="regime">${esc(s.regime)}</span></div>`).join('')||'<div class="empty">No signals returned.</div>';$('#signal-list').innerHTML=rows;$('#signals-table').innerHTML=`<table class="data-table"><thead><tr><th>Ticker</th><th>Direction</th><th>Confidence</th><th>Regime</th><th>Rationale</th></tr></thead><tbody>${signals.map(s=>`<tr><td><strong>${esc(s.ticker)}</strong></td><td class="direction ${(s.direction||'').toLowerCase()}">${esc(s.direction)}</td><td>${Number(s.confidence).toFixed(1)}%</td><td>${esc(s.regime)}</td><td>${esc(s.rationale)||'—'}</td></tr>`).join('')||'<tr><td colspan="5">No signals yet.</td></tr>'}</tbody></table>`}
async function loadPortfolio(){try{const p=await get('/portfolio');$('#portfolio-data').innerHTML=`<div class="kv"><div><span>Cash</span><strong>${money(p.cash_usd)}</strong></div><div><span>Equity</span><strong>${money(p.equity)}</strong></div><div><span>Return</span><strong>${Number(p.total_return_pct).toFixed(2)}%</strong></div><div><span>Exposure</span><strong>${Number(p.exposure_pct).toFixed(2)}%</strong></div></div><table class="data-table"><thead><tr><th>Ticker</th><th>Direction</th><th>Size</th><th>Status</th><th>P&L</th></tr></thead><tbody>${(p.trade_log||[]).slice().reverse().map(t=>`<tr><td>${esc(t.ticker)}</td><td>${esc(t.direction)}</td><td>${money(t.size_usd)}</td><td>${esc(t.status)}</td><td>${t.pnl_usd==null?'—':money(t.pnl_usd)}</td></tr>`).join('')||'<tr><td colspan="5">No trades yet.</td></tr>'}</tbody></table>`;$('#equity').textContent=money(p.equity);$('#return').textContent=`${Number(p.total_return_pct).toFixed(2)}%`;$('#exposure').textContent=`${Number(p.exposure_pct).toFixed(2)}%`;$('#positions').textContent=p.open_positions}catch(e){$('#portfolio-data').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function loadRisk(){try{const r=await get('/risk-log');const events=r.active_events||[];$('#risk-data').innerHTML=`${events.length?`<div class="risk-banner">${events.length} active risk event${events.length>1?'s':''}</div>`:''}${(r.decisions||[]).slice(-12).reverse().map(d=>`<div class="diag"><strong>${esc(d.ticker||'PORTFOLIO')}</strong> · ${esc(d.reason||d.message||JSON.stringify(d))}</div>`).join('')||'<div class="empty">No risk decisions logged.</div>'}`}catch(e){$('#risk-data').innerHTML=`<div class="empty">${esc(e.message)}</div>`}try{const l=await get('/learning/status');$('#learning-data').innerHTML=`<div class="kv"><div><span>Closed trades</span><strong>${l.closed_trades_logged}</strong></div><div><span>Wins / losses</span><strong>${l.wins} / ${l.losses}</strong></div><div><span>Ready to retrain</span><strong>${l.ready_to_retrain?'YES':'NO'}</strong></div><div><span>Weights</span><strong>S ${Number(l.current_weights.sentiment).toFixed(2)} · T ${Number(l.current_weights.technical).toFixed(2)} · R ${Number(l.current_weights.regime).toFixed(2)}</strong></div></div>`}catch(e){$('#learning-data').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function health(){try{const h=await get('/health');const ok=h.status==='ok'&&h.persistence?.status==='ok';$('#health').innerHTML=`<span class="status-dot"></span> API ${ok?'online':'degraded'} · SQLite ${esc(h.persistence?.status||'unknown')}`;$('#last-refresh').textContent=new Date().toLocaleTimeString()}catch(e){$('#health').innerHTML='<span class="error-dot">●</span> API unavailable';$('#last-refresh').textContent='offline'}}
async function scan(){const btn=$('#ingest');btn.disabled=true;btn.textContent='Scanning…';try{const r=await fetch(api()+'/ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tickers:{AAPL:'stock',TSLA:'stock',NVDA:'stock',SPY:'stock',BTC:'crypto',ETH:'crypto'},lookback_bars:90,news_lookback_hours:48})});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.detail?.message||data.detail||'Ingestion failed');signals=data.signals||[];renderSignals();$('#diagnostics').innerHTML=Object.entries(data.diagnostics||{}).map(([t,d])=>`<div class="diag"><strong>${esc(t)}</strong> · ${d.ok?'OK':'SKIPPED'} · price: ${esc(d.price_source_used||'—')} · news: ${esc(d.news_source_used||'—')}</div>`).join('')||'<div class="empty">No diagnostics.</div>';await loadPortfolio();await health();toast(`Scan complete · ${signals.length} signals`)}catch(e){$('#diagnostics').innerHTML=`<div class="diag error-text">${esc(e.message)}</div>`;toast(e.message,true)}finally{btn.disabled=false;btn.textContent='Run market scan'}}
async function retrain(){const b=$('#retrain');b.disabled=true;b.textContent='Training…';try{const r=await fetch(api()+'/learning/retrain',{method:'POST'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||'Retraining unavailable');await loadRisk();toast('Learning model retrained')}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent='Retrain'}}
$('#refresh').onclick=async()=>{await Promise.all([health(),loadPortfolio(),loadRisk()]);toast('Dashboard refreshed')};$('#refresh-portfolio').onclick=loadPortfolio;$('#refresh-risk').onclick=loadRisk;$('#retrain').onclick=retrain;$('#ingest').onclick=scan;$('#scan-signals').onclick=scan;health();loadPortfolio();
refreshTimer=setInterval(()=>{health();loadPortfolio()},30000);window.addEventListener('beforeunload',()=>clearInterval(refreshTimer));